openapi: 3.0.0
servers:
  - url: 'http://127.0.0.1:3001'
    variables: {}
info:
  version: 0.0.1
  title: 'Naomesh Seduce NestJS Transform API'
  description: Specification
  termsOfService: ''
    # Contact information: name, email, URL.
  contact:
    name: API Support
    email: lucas.rouretperso@gmail.com
    url: https://github.com/naomesh
  # Name of the license and a URL to the license description.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: node
    description: everything related to node
paths:
  /v1/{nodeID}/live-consumption:
    parameters:
      - $ref: '#/components/parameters/nodeID'
    get:
      description: It sums PSU 0 and PSU 1
      summary: Get live consumption of node. It sums PSU 0 and PSU 1
      parameters: []
      operationId: getLiveConsumptionOfNode
      tags:
        - node
      responses:
        '200':
          description: sucessful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Live consumption of node {{nodeID}}"
                  unit:
                    type: string
                    example: "watt"
                  data:
                    type: number
                    example: 114.4
        '404':
          description: invalid node id, not found

  /v1/{nodeID}/consumption-diff:
    parameters:
      - $ref: '#/components/parameters/nodeID'
    get:
      summary: Get consumption of node
      description: It is in watt
      parameters:
        - in: query
          name: step
          schema:
            type: number
            example: 0.5
            default: 0.5
          description: number of seconde, granularity, step
        - in: query
          name: from
          schema:
            type: integer
            example: 2
            default: 2
          description: Number of hours, from now to get measures
      operationId: getConsumptionOfNode
      tags:
        - node
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Consumption of node {{nodeID}} from last {{from}} hours"
                  unit:
                    type: string
                    example: "watt"
                  sum:
                    type: number
                    example: 1100
                    description: Total consumption in kWh
                  data:
                    type: array
                    description: array of tuples, first is timestamp and secone is value in watt
                    example:
                      -
                        - 1675782805000
                        - 113.4
                    items:
                      type: array
                      items:
                        type: number
                      maxItems: 2
                      minItems: 2

        '400':
            description: invalid node id, not found
  /v1/{nodeID}/consumption:
    parameters:
      - $ref: '#/components/parameters/nodeID'
    get:
      summary: Get consumption of node with historical data
      description: historical data
      parameters:
        - in: query
          name: step
          schema:
            type: number
            example: 0.5
            default: 0.5
          description: number of s, granularity, step
        - in: query
          name: range # range=1675782805000:1675782805000,1675782806000:1675782906000...
          style: spaceDelimited
          explode: true
          schema:
            type: array
            items:
              type: string
              description: timestamp;timestamp
              example: 1675782805000:1675782805000,1675782806000:1675782906000
          description: Array of start;end
      operationId: getConsumptionOfNodeHistorical
      tags:
        - node
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Consumption of node {{nodeID}} from {{from}} hours"
                  unit:
                    type: string
                    example: "watt"
                  sum:
                    type: number
                    example: 1100
                    description: Total consumption in kWh
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        start:
                          type: integer
                          example: 1675782804000
                        end:
                          type: integer
                          example: 1675782805000
                        data:
                          type: array
                          description: array of tuples, first is timestamp and secone is value in watt
                          example:
                            -
                              - 1675782805000
                              - 113.4
                          items:
                            type: array
                            items:
                              type: number
                            maxItems: 2
                            minItems: 2
        '400':
          description: invalid node id, not found

  '/v1/live-consumption':
    get:
      operationId: getLiveConsumptionOfAllNodes
      description: Get live consumption of all nodes in watt specified by query parameter
      parameters:
        - in: query # https://stackoverflow.com/a/73469036
          name: nodes # nodes=ecotype-25_pdu-Z1.2,ecotype-24_pdu-Z1.2
          style: spaceDelimited
          explode: true
          schema:
            type: array
            items:
              type: string
              description: node id
              example: ecotype-25_pdu-Z1.2,ecotype-26_pdu-Z1.2
          description: Array of node ids
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Live consumption of nodes {{nodeID}}"
                  unit:
                    type: string
                    example: "watt"
                  data:
                    type: number
                    example: 114.4
        '404':
          description: Invalid ID supplied

  '/v1/live-production-solar-panels':
    get:
      description: Get production of solar panels
      operationId: getLiveProductionSolarPanels
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "Live production of solar panels"
                  unit:
                    type: string
                    example: "watt"
                  data:
                    type: number
                    example: 114.4

components:
  parameters:
    nodeID:
        name: nodeID
        in: path
        description: ID of the node
        required: true
        schema:
          type: string
          example: "ecotype-25_pdu-Z1.2"
  links: {}
  callbacks: {}


